version: '3.8'

services:
  gmail-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gmail-mcp-server
    volumes:
      - mcp-gmail:/gmail-server
      - ./gcp-oauth.keys.json:/gcp-oauth.keys.json:ro
    environment:
      - GMAIL_CREDENTIALS_PATH=/gmail-server/credentials.json
      - GMAIL_OAUTH_PATH=/gcp-oauth.keys.json
      - NODE_ENV=production
      - MCP_SERVER_MODE=http
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  mcp-gmail: